### ISSUE TITLE
Didn't receive a proper icon

### ISSUE THREAD

**Issue by benny-innofaith** [wgenial/mimetypeicons-nodejs#4]
**Reproducible steps:**
Go to https://mimetypeicons.gq/.ai

**Expected result:**
A 20x code with a image.

**Actual result:**
A 404 with the following HTML content:
```
Cannot GET /mimetypes-icons/32/application-postscript.png
```

**Comment by giovanigenerali** [comment]
@benny-innofaith sorry for the delay - fixed!

https://mimetypeicons.gq/.ai

https://mimetypeicons.gq/mimetypes-icons/32/application-postscript.png

**Comment by giovanigenerali** [comment]
fixed
