### ISSUE TITLE
Could you please add the icon for application/json

### ISSUE THREAD

**Issue by KingMario** [wgenial/mimetypeicons-nodejs#5]
Could you please add the icon for application/json. Generally it should look like "{;}"
![image](https://user-images.githubusercontent.com/3956876/53708673-85e24000-3e6f-11e9-9ba6-001f291641cb.png)
.

Thanks.

**Comment by giovanigenerali** [comment]
@KingMario the icon for json file is not available in [faenza-icon-theme](https://code.google.com/archive/p/faenza-icon-theme). 

Take a look at this project [file-extension-icon-svg](https://github.com/wgenial/file-extension-icon-svg), it uses [vscode-icons](https://github.com/vscode-icons/vscode-icons) and you can load icons from a wide range of extension files.

**Comment by KingMario** [comment]
Thanks a lot
